### ISSUE TITLE
Support % for min/max width and height

### ISSUE THREAD

**Issue by bokuweb** [bokuweb/react-resizable-box#22]

**Comment by mull** [comment]
@bokuweb how do you feel about this task? What needs to be done, how can it be done?

**Comment by bokuweb** [comment]
it need to convert `%` to `px`.　
It will take time

**Comment by mull** [comment]
Are you planning on working it anytime soon, or shall I start working on a PR if I find I need this functionality? Thanks

**Comment by bokuweb** [comment]
@mull Ummm. It is undecided.

> shall I start working on a PR if I find I need this functionality? Thanks

I really appreciate it!!thx!!

**Comment by travisdahl** [comment]
one thing i noticed is....
 when i have a resizable that only has top/bottom enabled as resizeable (the rest false) and i set a width to '100%'. it gets changed to a px value when i resize. since i dont have any resize enabled on the horizontal axis i would expect it to just leave it as a percentage.
