### ISSUE TITLE
Add `bounds` function

### ISSUE THREAD

**Issue by bokuweb** [bokuweb/react-resizable-box#46]
Add `bounds` function for resizing.

Also see https://github.com/bokuweb/react-rnd/issues/57

**Comment by kudlajz** [comment]
@bokuweb Are you able to somehow extract or expose [this function](https://github.com/bokuweb/react-draggable-custom/blob/master/lib/utils/positionFns.es6#L15) from `react-draggable-custom`? I wanted to at least try to implement the `bounds` into this component, but I would like to avoid repeating the code.. but since both `draggable` and `resizable` components do not have mutual dependencies, I guess there's no way around.

**Comment by bokuweb** [comment]
@kudlajz thanks. I had implemented `bounds` function to `react-resizable-decorator`(https://github.com/bokuweb/react-resizable-decorator) 

If you try implement this function to `react-resizable-box`, please reference this line https://github.com/bokuweb/react-resizable-decorator/blob/master/src/index.js#L221-L232

thanks!

**Comment by bokuweb** [comment]
If you need this function for `react-rnd`, I 'll  implemenet this function to next rnd version.Please give me some time.

**Comment by kudlajz** [comment]
@bokuweb Thanks.. and yeah, I need this functionality in `react-rnd`.. 😄

**Comment by bokuweb** [comment]
Implementation in progress...

**Comment by bokuweb** [comment]
Add @2.0-rc.2

**Comment by kudlajz** [comment]
@bokuweb Are you planning on releasing this into v4 of `react-rnd` or do we have to wait for v5?

**Comment by bokuweb** [comment]
@kudlajz I implement react-rnd, including this feature, now.(https://github.com/bokuweb/react-rnd/tree/v5.0) because , some api had broken.I 'm going to release react-rnd v5-rc In a few days.

**Comment by kudlajz** [comment]
@bokuweb Great, looking forward to it! 👍

**Comment by bokuweb** [comment]
@kudlajz Fix this bug on raect-rnd@v5.0.0-rc.1. please try it.

**Comment by kudlajz** [comment]
@bokuweb Works nice, thanks!
